version: '3.8'
services:
  gateway:
    build: ./gateway
    image: shareit/gateway
    restart: always
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: shareit/server
    restart: always
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=docker
      - SPRING_DATASOURCE_PASSWORD=docker

  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shareit