create table if not exists users
(
    user_id    bigint generated by default as identity
        constraint users_pk
            primary key,
    user_name  varchar(255) not null,
    user_email varchar(512) not null
        constraint uq_user_email
            unique
);

create table if not exists requests
(
    request_id          bigint generated by default as identity
        constraint requests_pk
            primary key,
    request_description varchar(512),
    requestor_id        bigint    not null
        constraint requests_users_null_fk
            references users
            on delete cascade,
    request_created     timestamp not null
);

create table if not exists items
(
    item_id          bigint generated by default as identity
        constraint items_pk
            primary key,
    item_name        varchar(255) not null,
    item_description varchar(512),
    is_available     boolean      not null,
    owner_id         bigint       not null
        constraint items_users_null_fk
            references users
            on delete cascade,
    request_id       bigint
        constraint items_requests_null_fk
            references requests
            on delete set null
);

create table if not exists bookings
(
    booking_id     bigint generated by default as identity
        constraint bookings_pk
            primary key,
    booking_start  timestamp   not null,
    booking_end    timestamp   not null,
    item_id        bigint      not null
        constraint bookings_items_null_fk
            references items
            on delete cascade,
    booker_id      bigint      not null
        constraint bookings_users_null_fk
            references users
            on delete cascade,
    booking_status varchar(10) not null
);

create table if not exists comments
(
    comment_id      bigint generated by default as identity
        constraint comments_pk
            primary key,
    comment_text    varchar(1025) not null,
    item_id         bigint        not null
        constraint comments_items_null_fk
            references items
            on delete cascade,
    author_id       bigint        not null
        constraint comments_users_null_fk
            references users
            on delete cascade,
    comment_created timestamp     not null
);




